# Generated by Django 3.1.2 on 2020-11-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=200)),
                ('vacancy_desc', models.TextField()),
                ('vacancy_start_date', models.DateTimeField(auto_now=True)),
                ('vacancy_end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='question_text',
        ),
        migrations.AddField(
            model_name='companies',
            name='company_name',
            field=models.CharField(default='undefinde Company name ', max_length=50),
        ),
        migrations.DeleteModel(
            name='Vanacies',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='vacancy_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.companies'),
        ),
    ]
