# Generated by Django 3.1.2 on 2020-11-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201111_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='vacancy_start_date',
            field=models.DateTimeField(),
        ),
    ]
