# Generated by Django 3.1.2 on 2020-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201111_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='vacancy_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='vacancy_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
